version: 1.0.{build}

build_script:

- cmd: echo "AppVeyor"

test: off



#---------------------------------#

#  Skip builds for doc changes    #

#---------------------------------#

skip_commits:

  # Regex for matching commit message

  message: /\(doc\).*/

environment:
  APPVEYOR_RDP_PASSWORD: <your password>

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
